version: '3.1'

services:
 db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inter
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - 5432:5432